# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-30 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factguesser', '0002_auto_20171030_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposition',
            name='tosi',
            field=models.BooleanField(default=True),
        ),
    ]
