# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-31 14:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factguesser', '0004_auto_20171030_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposition',
            name='highlighted',
        ),
    ]
